language: python
python: '3.4'
sudo: required
services:
  - docker
before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - pip3 install sqflint
script:
  - sqflint --directory addons --exit w
  - docker-compose run build
  - docker-compose run package
  - ls bin
